spring.application.name=stockflow-api

spring.datasource.url=jdbc:postgresql://localhost:5432/stockflow
spring.datasource.username=stockflow
spring.datasource.password=stockflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true